version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_USERNAME=${CONFLUENCE_USERNAME}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - REDIS_URL=redis://redis:6379
      - ACROLINX_API_URL=${ACROLINX_API_URL}
      - ACROLINX_API_TOKEN=${ACROLINX_API_TOKEN}
      - ACROLINX_GUIDANCE_PROFILE=${ACROLINX_GUIDANCE_PROFILE}
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python -m flask run --host=0.0.0.0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
